version: '3.4'
services:
  shop:
    image: shop_front
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - $PWD:/app
